---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: build-artifacts

outputs:
- name: deployment-artifacts

run:
  path: attendee-service-source/ci/tasks/deploy.sh

