---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/pivotal-enablement/attendee-service
    branch: smoke_tests

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml
- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - task: deploy
    file: attendee-service-source/ci/tasks/deploy.yml
    params:
      CF_API: api.run.pez.pivotal.io
      CF_USER: {{cf-user}}
      CF_PASSWORD: {{cf-password}}
      CF_ORG: pivot-twhitney
      CF_SPACE: pal
- name: smoke_test
  plan:
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke_test.yml
    params:
      ATTENDEE_SERVICE_URL: https://attendee-service-clotty-megalopolis.cfapps.pez.pivotal.io 
